services:
  node:
    build:
      context: .
      dockerfile: "./docker/nodejs/Dockerfile"
    container_name: "ether_webserver"
    restart: 'no'
    ports:
      - 80:3000
    volumes:
      - ./:/app
